src/ofbx.cpp

This PR contains the fixes I needed to make to compile the program on a mac.
From most to least important:
- Add missing `#include <string>`
- Add `static` to header declarations for static functions
- Add optional define `OFBX_DEFINE_MAKE_UNIQUE` which defines `std::make_unique`
- Add `override` declarations where they are missing

Fixes for mac build

---

src/ofbx.cpp
src/ofbx.h

One of the files I'm testing with has a mesh in which most of the vertices are not indexed.  This caused a segfault when OpenFBX tries to reverse its index permutation for skinning.
It's been fixed by enlarging the reverse permutation to contain mappings for all of the original vertices, regardless of how many were actually used.  The skinning lookup then checks for unmapped vertices and ignores their skinning weights.
Here's the (zipped) file for reference:
[UnusedVertices.zip](https://github.com/nem0/OpenFBX/files/1288587/UnusedVertices.zip)

Fix segfault on files with unused vertices

---

src/ofbx.cpp
src/ofbx.h

When calculating node transforms, the post rotation wasn't inverted before.  This probably wasn't noticed because most nodes don't have a post rotation.

Fix inverted post rotation

---

src/ofbx.cpp

Thank you for OpenFBX. I'm using it in my own Ylikuutio 3D engine. These bugfixes enable compiling OpenFBX on Clang and fix warnings about missing `override` specifiers. Tested with clang version 3.8.1-24 (tags/RELEASE_381/final).

Enable compiling on Clang and fix warnings about missing `override` specifiers

---

src/ofbx.cpp
src/ofbx.h

Just a small improvement that adds support for importing up to 4 geometry UVs channels. It's very useful for importing separate texcoords for lightmap uvs.

Add support for importing up to 4 UVs channels

---

src/ofbx.cpp
src/ofbx.h

Changes:
- Reading FBX global settings
- Support custom frame rate for the scenes
- Node local transformation
- Node local transformation with scaling vector
Exposed global settings can be used for example to convert Right-Handed models to Left-Handed system.
This fixes: #12

Global FBX settings

---

src/ofbx.cpp

Simply converted all the
prop = std::make_unique<Property>();
into the equivalent, shorter and more c++11 compatible
prop(new Property());

Added missing include and made it c++11 compatible

---

demo/main.cpp
src/ofbx.cpp
src/ofbx.h

- Refactor geometry parsing and construction.
- Add face indices to `Geometry` interface.
- Make mesh triangulation optional.
When mesh triangulation is enabled (default case) face indices may be ignored. So this patch doesn't require any changes in client code.

Make mesh triangulation optional

---

src/ofbx.cpp
src/ofbx.h

- proper return type (bool instead of int)
- declare destructors "override" where applicable
- ensure data is initialized
- fix order of constructor initialization
- remove unused variables

Some basic static analysis fixes

---

src/ofbx.cpp

Original fix: a55a9553e0519cb289a3d5f42aede558d75dfaa9
Overwritten in: b934ba81ce129a5e491a59e672888bd05953a262

Re-fix fix for invalid vertices in splat()

---

src/ofbx.cpp

this should be a copy&paste error. Cause blend shape import error from text format files.

fix error when loading from text mode fbx files.

---

demo/main.cpp

Context: was failing to run the demo when using input args. If the buffer is left uninitialized you can end up with file paths that are padded with junk instead of getting null-terminated:
`C:\test.fbxÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌÌ …

[demo] clear filepath buffer to ensure null-terminated string

---

src/ofbx.h

In order to use `ofbx::IScene` ptr's with standard c++ lifetime constructs like `std::unique_ptr` or `std::shared_ptr`, it has to have a public destructor.
With this fix, scenes can be used like so:
`auto scene = std::unique_ptr<ofbx::IScene>(ofbx::load(fbxDataPtr, fbxDataSize, 0));`
which is more convenient than managing life time manually.

Add compatibility with std::unique_ptr.

---

src/ofbx.cpp

This bug led to a load of incorrect normal vectors in some files exported from Maya.

Fix a bug in patchAttributes function

---

CMakeLists.txt
openfbxConfig.cmake.in

miniz was replaced with libdeflate in https://github.com/nem0/OpenFBX/commit/7f64c109fd54d51d6c7ec698456c7a12e762ea50

Replace miniz dependency with libdeflate in CMake

---

src/ofbx.cpp
src/ofbx.h

While internal functions, like `tokenize()` and `tokenizeText()` already used the correct size type, the main `load()` function used `int` as size type. This restricts the size of supported FBX files to 2GB.
With this small fix, larger files can be processed. I've tested this succesfully with a 3.5GB FBX file.

Load function: change size parameter type from int to usize

---

src/ofbx.cpp
src/ofbx.h

- Fixed misaligned reads caused by casting char* to float* by introducing `read_value()` that uses a union and memcpy to address the issue.
- Fixed a bug in reading skeleton roots by adding a "Root" type check for skeleton joint roots in addition to "LimbNode".
- ~~Updated to cross-platform typedefs~~
- Enabled double precision support by removing hard-coded preprocessor directives.
- Improved the cross-platform compatibility of the isEndLine() function.

Fix alignment issues in data reading and skeleton root identification

---

src/ofbx.cpp

Clang12 does not support `std::bit_cast`, so this change introduces a check for the `std::bit_cast` feature using the `__cpp_lib_bit_cast` macro, according to the documentation found at https://en.cppreference.com/w/cpp/feature_test

Fix build with Clang 12

---

src/ofbx.cpp

The issue stems from an oversight in https://github.com/nem0/OpenFBX/pull/96, resulting in a runtime error due to misalignment:
```
ofbx.cpp:595:12: runtime error: load of misaligned address 0x7fdf1b93581b for type 'const unsigned long', which requires 8 byte alignment
```

Fix alignment issue in read()

---

CMakeLists.txt

I added libdeflate to cmake using fetchcontent, this makes it much more straight forward in cloning and including OpenFBX into other projects, without manually installing dependencies

added automatic CMake import of libdeflate as source

---

src/ofbx.cpp
src/ofbx.h

Hey !
I have added a getHeaders() method to be able to easily retreive headers data from FBX file (app, creator, FBX version...)
Here is how i use it in my own app that uses openfbx :
```
void fbx_mesh_loader::get_metadata(const ofbx::IScene* scene)
{
const ofbx::Headers* headers = scene->getHeaders();
if (headers)
{
int fbxHeaderVersion = headers->fbxHeaderVersion;
int fbxVersion = headers->fbxVersion;
int encryptionType = headers->encryptionType;
char* creator = headers->creator;
char* creationTime = headers->creationTime;
char* documentUrl = headers->documentUrl;
char* srcDocumentUrl = headers->srcDocumentUrl;
char* originalApplicationVendor = headers->originalApplicationVendor;
char* originalApplicationName = headers->originalApplicationName;
char* originalApplicationVersion = …
```

Add getHeaders() method + parsing headers logic
